name: Sync External Branches

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openpilot repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"


      - name: Sync from sunnyhaibin
        run: |
          git remote add sunnyhaibin https://github.com/sunnyhaibin/openpilot.git || true
          git fetch sunnyhaibin dev-c3
          git checkout -B dev-c3 sunnyhaibin/dev-c3
          git push origin dev-c3 --force
          git fetch sunnyhaibin tn
          git checkout -B tn sunnyhaibin/tn
          git push origin tn --force

      - name: Sync pre-build from dragon-community
        run: |
          git remote add dragon-community https://github.com/dragonpilot-community/dragonpilot.git || true
          git fetch dragon-community pre-build
          git checkout -B pre-build dragon-community/pre-build
          git push origin pre-build --force
